# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: HW2-CSC510 Autopep8 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Autopep8
      run: |
        pip install autopep8
    - name: Run autopep8
      run: |
        autopep8 --aggressive --diff rand.py hw2_debugging.py > ./post_traces/autopep8_trace.txt
    - name: Upload autopep8 Trace
      uses: actions/upload-artifact@v3
      with:
        name: autopep8-trace
        path: ./post_traces/autopep8_trace.txt
        if-no-files-found: warn  

