
name: HW2-CSC510 Pyright Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Pyright
      run: |
        pip install pyright
      
    - name: Run Pyright
      run: pyright --verbose hw2_debugging.py rand.py > ./post_traces/pyright_trace.txt
    - name: Upload Pyright Trace
      uses: actions/upload-artifact@v3
      with:
        name: pyright-trace
        path: ./post_traces/pyright_trace.txt
        if-no-files-found: warn
